Repository CouncilDataProject/cdp-scrapers, pull requests merged in 2021-08, with the labels that each got.

#14 feature/more-docs-and-get-events-for-seattle
  cdp_scrapers/instances/empty.py
  cdp_scrapers/instances/seattle.py
Labels: documentation, enhancement

#15 admin/more-docs-and-doc-configuration
  README.md
  SeattleScraperGetVideoUris.ipynb
  cdp_scrapers/instances/seattle.py
  cdp_scrapers/legistar_utils.py
  docs/conf.py
  docs/index.rst
  setup.py
Labels: documentation

#16 bug/scraper-cleaner-ingestion-models
  cdp_scrapers/legistar_utils.py
Labels: bug

#18 bugfix/use-canonical-tzs
  cdp_scrapers/instances/seattle.py
  cdp_scrapers/legistar_utils.py
Labels: bug

#20 feature/legistar-utils-cleanup-and-scrapers-dict-init
  cdp_scrapers/instances/__init__.py
  cdp_scrapers/instances/kingcounty.py
  cdp_scrapers/instances/seattle.py
  cdp_scrapers/legistar_utils.py
Labels: documentation, enhancement

#17 bug/scraper-cleaner-ingestion-models-2
  cdp_scrapers/legistar_utils.py
Labels: bug, enhancement

#21 feature/strictly-type-get-video-uris-return
  cdp_scrapers/instances/kingcounty.py
  cdp_scrapers/instances/seattle.py
  cdp_scrapers/legistar_utils.py
  cdp_scrapers/types.py
Labels: enhancement
