Repository CouncilDataProject/cdp-scrapers, pull requests merged in 2022-01, with the labels that each got.

#56 bugfix/king-county-position-3-image-uri
  cdp_scrapers/instances/kingcounty-static.json
Labels: bug

#58 feature/seattle-sara-nelson
  cdp_scrapers/instances/seattle-static.json
  cdp_scrapers/legistar_utils.py
Labels: enhancement

#61 admin/king-county-election-update
  cdp_scrapers/instances/kingcounty-static.json
Labels: documentation, enhancement

#64 bugfix/seattle-nelson-picture-uri
  cdp_scrapers/instances/seattle-static.json
Labels: bug

#68 feature/portland-supporting-files
  cdp_scrapers/instances/portland.py
Labels: enhancement

#69 bugfix/resolve-person-alias
  cdp_scrapers/instances/seattle.py
  cdp_scrapers/legistar_utils.py
  cdp_scrapers/scraper_utils.py
Labels: bug
